--- Makefile.orig	2014-03-21 12:03:00.894370998 +0200
+++ Makefile	2014-03-21 12:03:19.149384455 +0200
@@ -19,7 +19,7 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 
-METHPIPE_ROOT = $(shell pwd)
+METHPIPE_ROOT = $(EASYBUILDBUILDPATH)
 
 all:
 	@make -C src METHPIPE_ROOT=$(METHPIPE_ROOT) OPT=1
