--- FVCOM_source/makefile.orig	2014-11-05 14:58:32.000000000 -0500
+++ FVCOM_source/makefile	2018-06-15 13:49:15.757757968 -0400
@@ -40,7 +40,7 @@
 
 .F.o:
 	$(CPP) $(CPPARGS) $(PETSC_FC_INCLUDES) $*.F > $*.f90
-	$(FC)  -c $(FFLAGS) $(INCS) $*.f90
+	$(FC)  -c $(FFLAGS) $(INCS) $(MPIINCS) $*.f90
 	\rm $*.f90
 
 .F90.o:
