##
# Copyright 2009-2017 Ghent University
#
# This file is part of EasyBuild,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://www.vscentrum.be),
# Flemish Research Foundation (FWO) (http://www.fwo.be/en)
# and the Department of Economy, Science and Innovation (EWI) (http://www.ewi-vlaanderen.be/en).
#
# http://github.com/hpcugent/easybuild
#
# EasyBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation v2.
#
# EasyBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EasyBuild.  If not, see <http://www.gnu.org/licenses/>.
##

"""
Script for autogenerating the list of OpenKIM models and model drivers.

The script writes a file 'openkim-filelist.include' which should
be manually inserted under the source line in the EasyConfig file.

Author: Jakob Schiotz, Dept. of Physics, Technical University of Denmark.
Email: schiotz@fysik.dtu.dk
"""

try:
    # The EasyBuild project is using Python 2
    from urllib2 import urlopen
except ImportError:
    # But somebody (e.g. the author) might have loaded Python 3
    from urllib.request import urlopen
import json
import time

query = b'&fields={"kimcode":1,"kim-api-version":1,"driver":1}&database=obj&query={"type":"mo"}'
#query = b'&database=obj&query={"type":"mo"}'
url = 'https://query.openkim.org/api'
timeout = 60
url_fd = urlopen(url, data=query, timeout=timeout)
models = json.loads(url_fd.read().decode('ascii'))
drivers = {x['driver']['kimcode'] for x in models if x['kim-api-version'] >= "1.6" and x['driver']}
models = [x['kimcode'] for x in models if x['kim-api-version'] >= "1.6"]

with open("openkim-filelist.include", "w") as outfile:
    outfile.write("# AUTOGENERATED ON: %s UTC\n" % time.asctime(time.gmtime()))
    outfile.write("sources += [\n")
    outfile.write("    #\n")
    outfile.write("    # Model drivers\n")
    outfile.write("    #\n")
    for m in sorted(drivers):
        kimfile = m[-19:] + '.tgz'
        assert kimfile.startswith('MD_')
        outfile.write("    '%s',  # %s\n" % (kimfile, m[:-21]))
    outfile.write("    #\n")
    outfile.write("    # Models\n")
    outfile.write("    #\n")
    for m in sorted(models):
        kimfile = m[-19:] + '.tgz'
        assert kimfile.startswith('MO_')
        outfile.write("    '%s',  # %s\n" % (kimfile, m[:-21]))
    outfile.write("]\n")
    outfile.write("# END OF AUTOGENERATED CODE.\n")
