from urllib.request import urlopen
import json
import time

query = b'&fields={"kimcode":1,"kim-api-version":1,"driver":1}&database=obj&query={"type":"mo"}'
#query = b'&database=obj&query={"type":"mo"}'
url = 'https://query.openkim.org/api'
timeout = 60        
# We should maybe do some error handling here?
url_fd = urlopen(url, data=query, timeout=timeout)
models = json.loads(url_fd.read().decode('ascii'))
drivers = {x['driver']['kimcode'] for x in models if x['kim-api-version'] >= "1.6" and x['driver']}
models = [x['kimcode'] for x in models if x['kim-api-version'] >= "1.6"]

with open("openkim-filelist.include", "w") as outfile:
    outfile.write("# AUTOGENERATED ON: %s UTC\n" % time.asctime(time.gmtime()))
    outfile.write("sources += [\n")
    outfile.write("    #\n")
    outfile.write("    # Model drivers\n")
    outfile.write("    #\n")
    for m in sorted(drivers):
        kimfile = m[-19:] + '.tgz'
        assert kimfile.startswith('MD_')
        outfile.write("    '%s',  # %s\n" % (kimfile, m[:-21]))
    outfile.write("    #\n")
    outfile.write("    # Models\n")
    outfile.write("    #\n")
    for m in sorted(models):
        kimfile = m[-19:] + '.tgz'
        assert kimfile.startswith('MO_')
        outfile.write("    '%s',  # %s\n" % (kimfile, m[:-21]))
    outfile.write("]\n")
