name: analyze
on: [pull_request]

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    # Analyze PR with tagbot.py that outputs a json file with results of tags and PR diff.
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout merged PR state
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install gitpython

      - name: Run analysis
        run: |
          python .github/workflows/analyze.py --output analysis.json
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Upload analysis artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: analysis
          path: analysis.json
          retention-days: 1
